import { CreateMemoDto } from '../../src/modules/memo/dto/createMemo.dto';

export const memoStub: CreateMemoDto = {
	Advance: 150,
	Commission: 230,
	Consignee: 'test',
	Consignor: 'testor',
	Driver_name: 'test driver',
	Drop_location: 'test city',
	Guide_rupees: 230,
	Height_charge: 240,
	Height_freight: 345,
	Other_expenses: 565,
	Owner_address: 'test address',
	Owner_name: 'test owner',
	Owner_number: 343443434,
	Particulars: 'test Particulars',
	Payment_location: 'test location',
	Pickup_location: 'test pickup',
	Remarks: 'my test remarks',
	Tapal: 560,
	Truck_number: 'KA_TESTE_3434',
	Weight: '5Ton',
	Weight_wage: 5000,
	Workout: 567,
	Total_collection: 56956,
	Inserted_date: new Date().toLocaleDateString('en-GB'),
	Memo_number: Math.floor(Math.random() * 10000),
};
